tasks:
  - name: Install Frontend Dependencies
    command: |
      cd frontend
      npm install
  - name: Install Backend Dependencies
    command: |
      pip install -r requirements.txt
  - name: Run Backend
    command: |
      uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    openMode: split-right
  - name: Run Frontend
    command: |
      cd frontend
      npm run dev
    openMode: split-right
ports:
  - port: 3000
    onOpen: open-browser
  - port: 8000
    onOpen: ignore
